version: '3'
services:
  water:
    build: .
    restart: always
    volumes:
        - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=WATER
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 150M
        reservations:
          cpus: '0.25'
          memory: 30M
    devices: 
      - /dev/tty.usbmodem23:/dev/tty.usbmodem23
      - /dev/tty.usbserial:/dev/tty.usbserial
  food:
    build: .
    restart: always
    volumes:
        - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=FOOD
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 150M
        reservations:
          cpus: '0.25'
          memory: 30M
    devices:
      - /dev/tty.usbmodem201201011:/dev/tty.usbmodem201201011
        # - /dev/tty.usbmodem201201011:/dev/tty.usbmodem201201011
        # - /dev/tty.usbserial:/dev/tty.usbserial
