# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\weight.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 241)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(310, 20, 281, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 81, 41))
        self.label_3.setObjectName("label_3")
        self.input_weight_ip_address = QtWidgets.QLineEdit(self.groupBox)
        self.input_weight_ip_address.setGeometry(QtCore.QRect(120, 30, 151, 31))
        self.input_weight_ip_address.setObjectName("input_weight_ip_address")
        self.label_weight_datetime = QtWidgets.QLabel(self.groupBox)
        self.label_weight_datetime.setGeometry(QtCore.QRect(120, 70, 161, 31))
        self.label_weight_datetime.setObjectName("label_weight_datetime")
        self.label_weight_value = QtWidgets.QLabel(self.groupBox)
        self.label_weight_value.setGeometry(QtCore.QRect(120, 110, 161, 21))
        self.label_weight_value.setObjectName("label_weight_value")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 291, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 81, 31))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 81, 41))
        self.label_6.setObjectName("label_6")
        self.input_rfid_ip_address = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_rfid_ip_address.setGeometry(QtCore.QRect(120, 30, 161, 31))
        self.input_rfid_ip_address.setObjectName("input_rfid_ip_address")
        self.label_rfid_value = QtWidgets.QLabel(self.groupBox_2)
        self.label_rfid_value.setGeometry(QtCore.QRect(120, 110, 161, 21))
        self.label_rfid_value.setObjectName("label_rfid_value")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 101, 31))
        self.label_5.setObjectName("label_5")
        self.input_rfid_ip_address_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_rfid_ip_address_2.setGeometry(QtCore.QRect(120, 70, 101, 31))
        self.input_rfid_ip_address_2.setObjectName("input_rfid_ip_address_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(230, 70, 41, 31))
        self.label_7.setObjectName("label_7")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(310, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(460, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "秤重儀"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.label_2.setText(_translate("MainWindow", "Datetime:"))
        self.label_3.setText(_translate("MainWindow", "Value:"))
        self.input_weight_ip_address.setText(_translate("MainWindow", "192.168.1.100:5000"))
        self.label_weight_datetime.setText(_translate("MainWindow", "Unconnect"))
        self.label_weight_value.setText(_translate("MainWindow", "Unconnect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "RFID"))
        self.label_4.setText(_translate("MainWindow", "IP:"))
        self.label_6.setText(_translate("MainWindow", "UID:"))
        self.input_rfid_ip_address.setText(_translate("MainWindow", "192.168.1.101:5000"))
        self.label_rfid_value.setText(_translate("MainWindow", "Unconnect"))
        self.label_5.setText(_translate("MainWindow", "ScanTime:"))
        self.input_rfid_ip_address_2.setText(_translate("MainWindow", "50"))
        self.label_7.setText(_translate("MainWindow", "ms"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))

